# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Lukas Murdock
logo:               # Logo image URL
email:              lukas@lukasmurdock.com
description:        This is the website of Lukas Murdock, designer, developer, and marketer helping you do work that matters for people who care.
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://lukasmurdock.com' # The base hostname & protocol for your site
twitter_username:   MurdockLukas
instagram_username: lukasauras.rex
linkedin_username: lukas-murdock

markdown:  kramdown
permalink: /:title/
# permalink: pretty
highlighter: rouge
# paginate:  13
sass:
  style: compressed

# last_modified_at: iso 8601 current time

gems:
  # - jekyll-paginate
  - jekyll/tagging
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

include:
  - _pages
  - _teardowns

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename
  - scope:
      path: '_teardown'
    values:
      permalink: /teardown/:basename