export const CHASE_TUNING = {
  capturePresentationDuration: 0.8,
  captureGraceDuration: 1.8,
  reinforcementCaptureGraceDuration: 1.35,
  respawnCaptureGraceDuration: 0.8,
  maximumPursuers: 3,
  escalationTimes: [0, 20, 45] as const,
  accuracyRamp: {
    startTime: 30,
    endTime: 45,
    predictionTime: 0.38,
    targetReactionRate: 4,
    lowSpeedTurnRate: 1.65,
    highSpeedTurnRate: 0.9,
    closeRangeSteeringFloor: 0.5,
  },
  pursuer: {
    radius: 1.25,
    maximumSpeed: 30,
    offRoadMaximumSpeed: 18,
    acceleration: 7.5,
    deceleration: 13,
    predictionTime: 0.32,
    targetReactionRate: 3.2,
    maximumCatchUpSpeed: 1.8,
    closeRangeSpeedAdvantage: 1.25,
    lowSpeedTurnRate: 1.55,
    highSpeedTurnRate: 0.82,
    stuckSpeed: 3,
    stuckDistance: 12,
    stuckDuration: 1.25,
    collisionBurstCount: 3,
    collisionBurstWindow: 1.5,
    collisionEpisodeCooldown: 0.25,
  },
} as const;
